#build VEINMATCHJNI
LOCAL_PATH :=$(call my-dir)
include $(CLEAR_VARS)

LOCAL_MODULE:=VEINMATCHJNI

LOCAL_SRC_FILES :=VeinMatchJni.cpp
LOCAL_C_INCLUDES += $(LOCAL_PATH)
LOCAL_LDLIBS := $(LOCAL_PATH)/libVEINMATCH.so
LOCAL_LDLIBS += -llog

include $(BUILD_SHARED_LIBRARY)



