/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wedone_sdk_VeinMatchLib */

#ifndef _Included_com_wedone_sdk_VeinMatchLib
#define _Included_com_wedone_sdk_VeinMatchLib
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     com_wedone_sdk_VeinMatchLib
 * Method:    vmInit
 * Signature: (IS)I
 */
JNIEXPORT jint JNICALL Java_com_wedone_sdk_VeinMatchLib_vmInit
  (JNIEnv *, jclass, jint, jshort);

/*
 * Class:     com_wedone_sdk_VeinMatchLib
 * Method:    vmStop
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wedone_sdk_VeinMatchLib_vmStop
  (JNIEnv *, jclass);

/*
 * Class:     com_wedone_sdk_VeinMatchLib
 * Method:    vmAddUserForMatch
 * Signature: ([BS[BSS)I
 */
JNIEXPORT jint JNICALL Java_com_wedone_sdk_VeinMatchLib_vmAddUserForMatch
  (JNIEnv *, jclass, jbyteArray, jshort, jbyteArray, jshort, jshort);

/*
 * Class:     com_wedone_sdk_VeinMatchLib
 * Method:    vmDeleteUserForMatch
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_com_wedone_sdk_VeinMatchLib_vmDeleteUserForMatch
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     com_wedone_sdk_VeinMatchLib
 * Method:    vmMatchWithAll
 * Signature: ([BS[BSB)I
 */
JNIEXPORT jint JNICALL Java_com_wedone_sdk_VeinMatchLib_vmMatchWithAll
  (JNIEnv *, jclass, jbyteArray, jshort, jbyteArray, jshort, jbyte);

/*
 * Class:     com_wedone_sdk_VeinMatchLib
 * Method:    vmMatchWithAllEx
 * Signature: ([BS[BSB[S)I
 */
JNIEXPORT jint JNICALL Java_com_wedone_sdk_VeinMatchLib_vmMatchWithAllEx
  (JNIEnv *, jclass, jbyteArray, jshort, jbyteArray, jshort, jbyte, jshortArray);

/*
 * Class:     com_wedone_sdk_VeinMatchLib
 * Method:    vmMatchInDepartment
 * Signature: (S[BS[BSB)I
 */
JNIEXPORT jint JNICALL Java_com_wedone_sdk_VeinMatchLib_vmMatchInDepartment
  (JNIEnv *, jclass, jshort, jbyteArray, jshort, jbyteArray, jshort, jbyte);

/*
 * Class:     com_wedone_sdk_VeinMatchLib
 * Method:    vmMatchByUserID
 * Signature: ([B[BS[BSB)I
 */
JNIEXPORT jint JNICALL Java_com_wedone_sdk_VeinMatchLib_vmMatchByUserID
  (JNIEnv *, jclass, jbyteArray, jbyteArray, jshort, jbyteArray, jshort, jbyte);

/*
 * Class:     com_wedone_sdk_VeinMatchLib
 * Method:    vmMatchByCardNo
 * Signature: ([B[BS[BSB)I
 */
JNIEXPORT jint JNICALL Java_com_wedone_sdk_VeinMatchLib_vmMatchByCardNo
  (JNIEnv *, jclass, jbyteArray, jbyteArray, jshort, jbyteArray, jshort, jbyte);

/*
 * Class:     com_wedone_sdk_VeinMatchLib
 * Method:    vmMatchTemplate
 * Signature: ([B[BB)I
 */
JNIEXPORT jint JNICALL Java_com_wedone_sdk_VeinMatchLib_vmMatchTemplate
  (JNIEnv *, jclass, jbyteArray, jbyteArray, jbyte);

/*
 * Class:     com_wedone_sdk_VeinMatchLib
 * Method:    vmMatchTemplateEx
 * Signature: ([B[BB[S)I
 */
JNIEXPORT jint JNICALL Java_com_wedone_sdk_VeinMatchLib_vmMatchTemplateEx
  (JNIEnv *, jclass, jbyteArray, jbyteArray, jbyte, jshortArray);

/*
 * Class:     com_wedone_sdk_VeinMatchLib
 * Method:    vmMatchTemplates
 * Signature: ([B[BSB)I
 */
JNIEXPORT jint JNICALL Java_com_wedone_sdk_VeinMatchLib_vmMatchTemplates
  (JNIEnv *, jclass, jbyteArray, jbyteArray, jshort, jbyte);

/*
 * Class:     com_wedone_sdk_VeinMatchLib
 * Method:    vmMatchTemplatesEx
 * Signature: ([B[BSB[S)I
 */
JNIEXPORT jint JNICALL Java_com_wedone_sdk_VeinMatchLib_vmMatchTemplatesEx
  (JNIEnv *, jclass, jbyteArray, jbyteArray, jshort, jbyte, jshortArray);

/*
 * Class:     com_wedone_sdk_VeinMatchLib
 * Method:    vmSetSecurityLevel
 * Signature: (SS)I
 */
JNIEXPORT jint JNICALL Java_com_wedone_sdk_VeinMatchLib_vmSetSecurityLevel
  (JNIEnv *, jclass, jshort, jshort);

#ifdef __cplusplus
}
#endif
#endif
